// Vue/vue-example/src/App.vue
<template>
  <div id="app">
    <p
        v-for="product in products"
        v-bind:key="product.id"
        v-bind:title="product.title"
    >
      {{product.title}}
    </p>
    <button v-on:click="addNewProduct">add</button>    
  </div>
</template>

<script>
  export default {
    name: 'App',
    data: function(){
      return {
        products: [],
        nextProductId: 0
      }
    },
    methods: {
      addNewProduct: function () {
        this.products.push({
          id: this.nextProductId++,
          title: "VUE TEST ITEM"
        })
      }
    }
  }
</script>

// Angular/angular-example/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'angular-test';
  products = Array<any>()
  addItem(){
    this.products.push("ANGULAR TEST ITEM");
  }
}

<div *ngFor="let product of products">
  <p>
    {{product}}
  </p>
</div>
<button (click)="addItem()">Add</button>
